### ISSUE TITLE
Miglioramenti grafici

### ISSUE THREAD

**Issue by giovannifil-64** [ggardin/tecweb#237]
Questa issue ha il solo scopo di segnare eventuali problemi/miglioramenti per la UI/UX del sito, in modo che prima della consegna, una volta completato il tutto, li si possano eventualmente sistemare. Ovviamente se anche voi trovate qualcosa che si può migliorare, segnatelo pure.
- [x] bottone di modifica nella stessa posizione. ora è sotto immagine in pagina film, sotto descrizione in pagine persona/collezione #240 
- [x] stesso nome per about: link in footer (ora "chi siamo"), breadcrumb e `h1`
- [x] stile liste in pagine: `user.html`, `lists.html`
- [x] Spostare il bottone di modifica della persona sotto l'immagine #240 
- [x] card orizzontali per ricerca #241
- [x] ridurre di brutto dimensione immagini da mobile, occupano troppo spazio! #240 
- [x] ridurre immagini in pagine dettaglio.. particolarmente fastidiosa nella pagina film: 1/3 dello spazio orizzontale è occupato solo dall'immagine #240 
- [x] stile bullet points per ruoli in film persona (Lasciamo come è)
- [x] Posizione e background del pulsante dell'account sminchiato (magari renderlo semplicemente cliccabile e non applicare lo sfondo)
- [x] `width` per form dati utente
- [ ] Cambiare la dimensione dell'icona nell'header tre pulsanti, ma mantenendo invariata a 2.75em l'area di interazione
- [x] Organizzare meglio i colori di sfondo dei bottoni (verde per quelli che eseguono get/post/etc, secondario con bordo per quelli che rimandano solamente a delle pagine) #241
- [x] Vedere se si possono avere due film per riga da mobile (NO) [Corretta introducendo le card orizzontali] #241
- [x] #352
- [x] La pagina dell'errore 500 dovrebbe avere lo stesso stile grafico della 404, in modo da avere una coerenza tra le varie pagine #240 
- [x] I due SVG nelle pagine di errore non sono centrati
- [x] Nella pagina "Film" a volte l'immagine non è centrata con il resto del contenuto (non so da cosa dipenda, non capita in maniera constante) #240 
- [x] L'header della pagina d'accesso sembra non avere le stesse dimensioni dell'header principale (c'è un piccolo shift a destra) [Boh sembra non si presenti più]
- [x] Nella pagina "Collezione" migliorare in contenuto delle card (Font leggermente più grande per il titolo, aumentare lo spazio tra i contenuti) #240 
- [x] Sempre nella pagine "Collezione" sarebbe meglio avere uno shift verticale delle card come nella ricerca, altrimenti è tutto troppo schiacciato [Risolto dogliendo la descrizione ;) ]
- [x] Ha senso avere il tasto home separato dal logo? (Il grande dibattito) [Sistemato sia avendo sia il tasto home che il logo, ma rimane si discorso della posizione sminchiata]
- [x] Mantenere mockup nelle schede all'interno della home o usare delle grafiche simili alla pagina 404 per mantenere lo stesso tipo di stile al sito? (mantenute, aggiornate ed ora cambiano in base al tema)
- [x] #313
- [x] Su iOS alcuni budget/incassi vengono rilevati come numeri di telefono, da quello che ho trovato va impostato il tag `<meta name="format-detection" content="telephone=no">` #240 
- [x] Sistemare il posizionamento dei bottoni mer muoversi avanti ed indietro tra i risultati #254  
- [x] Se i form non sono riempiti il bordo rosso non ha il bordo arrotondato come il field (bug di safari, non voglio stare dietro a sistemarlo. Eventualmente si vedrà alla fine)
- [x] #329
- [x] bloccare rapporto immagini
